### ISSUE TITLE
Unable to build Enzyme in Debug Mode

### ISSUE THREAD

**Issue by Nirhar** [EnzymeAD/Enzyme#773] opened 2022-08-05 03:37 UTC
To build enzyme in debug mode I am configuring cmake as below
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR="<path_to_llvm_project_built_in_debug_mode>/build/lib/cmake/llvm"
```

when I build it with `make`, I get the following error:
```
/usr/bin/ld: cannot find -lTBL_LINKED_LIBS-NOTFOUND
collect2: error: ld returned 1 exit status
```

Am i doing anything wrong or is this some bug in the repository?

**Comment by ludgerpaehler** [comment] 2022-08-09 00:33
Hey, did you manage to fix this by now?

Would be great to have a little more information to help you:

- What platform are you building on?
- Against which LLVM are you building, and which flags did you use to build said LLVM?

Best would be a starting from scratch, step-by-step description of how you attempted to build and then we should be able to help :))

**Comment by Nirhar** [comment] 2022-08-09 06:22
This issue occurs in the main branch. When I shifted to some stable release, say v0.0.33, this issue did not occur.

I am building on ubuntu 20.04 running on intel i5 processor. I am building against clang-11, which was built in debug mode.

To build clang 11 in debug mode I used the commands(this is inside `llvm-project/build`, where `llvm-project` is the repository I downloaded for llvm and clang 11) :
```
cmake -G Ninja ../llvm -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=X86 -DBUILD_SHARED_LIBS=On -DLLVM_USE_SPLIT_DWARF=On -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS=clang
ninja
```

and once the clang 11 binary is built in debug mode, I build enzyme in debug mode (These commands are run inside `Enzyme/enzyme/build`):
```  
cmake .. -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR="<path_to_llvm_project_built_in_debug_mode>/build/lib/cmake/llvm"
make
```

Now the above error is thrown in the main branch, but not in v0.0.33

**Comment by Nirhar** [comment] 2022-08-09 17:39
The error ocurrs in v0.0.34 too.

**Comment by ludgerpaehler** [comment] 2022-08-09 17:43
Would be great if you could bisect, when the error began appearing so we could fix it :)

**Comment by wsmoses** [comment] 2022-08-10 20:18
I'm not sure bisecting is useful since this is clearly a tablegen-related build.

@Nirhar can you can confirm what exact commit you're on, and that you're not using any patches or modifications to Enzyme. 

Moreover, can you reproduce the error you see in a docker container/file. Unfortunately our CI on Ubuntu 20.04 appears to succeed so this is a matter of attempting to replicate your environment.

**Comment by wsmoses** [comment] 2022-09-03 17:03
Closing for now, if this persists please reopen.

**Comment by ki9gpin** [comment] 2022-09-06 17:18
[CMakeCache.txt](https://github.com/EnzymeAD/Enzyme/files/9499353/CMakeCache.txt)

**Comment by ki9gpin** [comment] 2022-09-06 17:20
[CMakeCache.txt](https://github.com/EnzymeAD/Enzyme/files/9499366/CMakeCache.txt)
Enzyme cmake cache

**Closed** 2022-09-06 21:10 UTC
