### ISSUE TITLE
Branch mismatcharg fails to compile 

### ISSUE THREAD

**Issue by davidedelvento** [EnzymeAD/Enzyme#1839] opened 2024-04-18 13:12 UTC
Thanks @wsmoses for making the branch `mismatcharg` to debug my issue. I believe there is a typo in that branch which I think is so small that don't even deserve a PR (but I can open that if you so prefer).

This is the change I made and with it, the branch appears to work fine and produce the appropriate (extremely long) debug information. I hope to be able to sift through that log and find the problem without further bothering you.

```
diff --git a/enzyme/Enzyme/AdjointGenerator.h b/enzyme/Enzyme/AdjointGenerator.h
index 70514ba1..0bd29647 100644
--- a/enzyme/Enzyme/AdjointGenerator.h
+++ b/enzyme/Enzyme/AdjointGenerator.h
@@ -5283,7 +5283,7 @@ public:
         llvm::errs() << call << "\n";
         llvm::errs() << " number of arg operands != function parameters\n";
         EmitFailure("MismatchArgs", call.getDebugLoc(), &call,
-                    "Number of arg operands != function parameters\n", *call);
+                    "Number of arg operands != function parameters\n", call);
       }
     }
```
Thanks.

**Comment by wsmoses** [comment] 2024-04-19 21:38
Ah yup, fixed and merged.

Though can you post the log of the issue you found here so we can fix the cause of it upstream?

**Comment by wsmoses** [comment] 2024-04-20 18:12
Yup, if you can upload the module/reproducer I can fix whatever edge case
is causing it

**Comment by davidedelvento** [comment] 2024-04-20 21:44
Okay, so I did manage to reproduce the problem just (literally) messing around with the multisource example. 

The code is a bit of a mess and in fact it fails on a different call, but with identical error message. As in most of my previous reports it may be user incompetence more than Enzyme issue, but here you go.

Makefile:

```make
LINKER  = clang -fuse-ld=lld # ld.lld
CFLAGS  += -fopenmp=libomp -flto
LIBS    += -lomp
#ENZLLD   = ${HOME}/repositories/ENZYME/Enzyme-v0.0.103/enzyme/build-v0.0.104-with-llvm-v18.1.1-and-compiler-wrapper/Enzyme/LLDEnzyme-18.so
ENZLLD   = ${HOME}/repositories/ENZYME/Enzyme-v0.0.103/enzyme/build-head-debug/Enzyme/LLDEnzyme-18.so
#ENZCLANG = ${HOME}/repositories/ENZYME/Enzyme-v0.0.103/enzyme/build-v0.0.104-with-llvm-v18.1.1-and-compiler-wrapper/Enzyme/ClangEnzyme-18.so
ENZCLANG = ${HOME}/repositories/ENZYME/Enzyme-v0.0.103/enzyme/build-head-debug/Enzyme/ClangEnzyme-18.so

all : func.o main.o
	$(LINKER) -flto $(LDFLAGS) $(INLC) $? -o test.exe -v -Wl,--load-pass-plugin=$(ENZLLD)

main.o : main.c 
	$(CC) $(CFLAGS) $(INCL) -c $?

func.o : func.c 
	$(CC) $(CFLAGS) $(INCL) -c $?


.PHONY : clean
clean :
	rm -f *.o *.exe
```

func.c
```c
#include <stdio.h>
#include <stdlib.h>

#define DEBUG_PRINT_MACRO   if ( getenv( "MY_VERBOSE" ) != NULL  &&  atoi(getenv("MY_VERBOSE")) != 0 )

struct complex {
  double r;
  double i;
};

struct complex myblas_cdot(struct complex* x, struct complex *y, int n) {
  struct complex sum = { 0, 0 };
  for (int i=0; i<n; i++) {
    sum.r += x[i].r * y[i].r - x[i].i * y[i].i;
    sum.i += x[i].r * y[i].i + x[i].i * y[i].r;
  }
  DEBUG_PRINT_MACRO
    fprintf( stdout, " whatever ( %g, %g, %d )\n", x[0], y[0], n );

  return sum;
}

double myblas_cabs(struct complex x) {
    return x.r * x.r + x.i * x.i;
}
```

main.c
```c
#include <stdio.h>
#include <stdlib.h>

struct complex {
  double r;
  double i;
};

struct complex myblas_cdot(struct complex* x, struct complex *y, int n);
double myblas_cabs(struct complex x); 
void __enzyme_autodiff(void*, ...);

double dotabs(struct complex* alpha, struct complex* beta, int n) {
  struct complex prod = myblas_cdot(alpha, beta, n);
  return myblas_cabs(prod);
}

int main(int argc, char *argv[]) {
  int n = 3;

  struct complex *A = (struct complex*)malloc(sizeof(struct complex) * n);
  for(int i=0; i<n; i++)
   A[i] = (struct complex){(i+1), (i+2)};

  struct complex *grad_A = (struct complex*)malloc(sizeof(struct complex) * n);
  for(int i=0; i<n; i++)
   grad_A[i] = (struct complex){0,0};



  struct complex *B = (struct complex*)malloc(sizeof(struct complex) * n);
  for(int i=0; i<n; i++)
   B[i] = (struct complex){-3-i, 2*i};

  struct complex *grad_B = (struct complex*)malloc(sizeof(struct complex) * n);
  for(int i=0; i<n; i++)
   grad_B[i] = (struct complex){0,0};

  __enzyme_autodiff((void*)dotabs, A, grad_A, B, grad_B, n);
  printf("Value dotabs(A)[0] = %f\n", A[0].r);
  printf("Gradient dotabs(A)[0] = %f\n", grad_A[0].r);
  printf("Value dotabs(B)[0] = %f\n", B[0].r);
  printf("Gradient dotabs(B)[0] = %f\n", grad_B[0].r);

  return 0;
}
```

**Comment by wsmoses** [comment] 2024-05-01 22:07
@davidedelvento shjould be fixed by https://github.com/EnzymeAD/Enzyme/pull/1844 please reopen if it persists

**Closed** 2024-05-01 23:09 UTC

**Comment by davidedelvento** [comment] 2024-05-02 13:33
This particular problem is indeed solved. For my big code, it is now failing again, but the additional printing you included make it very clear why: `Enzyme: No augmented forward pass found for` a few more functions, namely `getenv`, `strtol`, `fwrite`.

Unless you advise differently, I'll look to what you have done with `fprintf` and attempt to do the same for these others and if successful make a PR, since there is no point to differentiate them (well maybe besides `strtol` if one is doing weird math things with strings)
